packages:
  hypre:
    prefer: [build_system=cmake]
  kynema-sgf:
    prefer: [+tiny_profile]
  trilinos:
    require: "~adelus~adios2~anasazi~basker~boost~chaco~complex~fortran~hypre~ifpack~intrepid2~mesquite~minitensor~mumps~nox~pamgen~panzer~phalanx~piro~python~rol~sacado~scorec~shylu~stokhos~stratimikos~strumpack~suite-sparse~superlu-dist~teko~tempus~thyra~x11~zoltan2 generator=ninja"
