packages:
  hypre:
    prefer: [build_system=cmake]
  kynema-sgf:
    prefer: [+tiny_profile]
  trilinos:
    require: "~adelus~adios2~amesos2~anasazi~basker~belos~boost~chaco~complex+exodus~fortran~hypre~ifpack2~intrepid2+kokkos~mesquite~minitensor~muelu~mumps~nox~pamgen~panzer~phalanx~piro~python~rol~sacado~scorec+shards~shylu+stk~stokhos~stratimikos~strumpack~suite-sparse~superlu-dist~teko~tempus~thyra+tpetra~x11+zoltan~zoltan2 generator=ninja"


