spack:
  concretizer:
    unify: false
    reuse: false 
  view: false
  specs:
    - 'kynema-driver~kynema_sgf_gpu~kynema_ugf_gpu~cuda'
    - 'kynema-driver+kynema_sgf_gpu~kynema_ugf_gpu+cuda cuda_arch=90'
    #- 'kynema-driver+kynema_sgf_gpu+kynema_ugf_gpu+cuda cuda_arch=90'
